version = "3.7.12"
runner.dialect = scala3

maxColumn = 100

rewrite.rules = [SortImports, RedundantBraces, SortModifiers, PreferCurlyFors]

rewrite.scala3.convertToNewSyntax = true

align.preset = more
align.openParenCallSite = false
align.openParenDefnSite = false

newlines.topLevelStatementBlankLines = [
  { blanks { before = 1 } }
]

docstrings.style = Asterisk
docstrings.wrap = no
